version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vicios_db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: vicios_server
    env_file:
      - packages/server/.env.development # Cambiar a .env.development en dev
    depends_on:
      - db
    ports:
      - "4000:4000"

  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    container_name: vicios_client
    env_file:
      - packages/client/.env.development # Cambiar a .env.development en dev
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  pgdata:
